TripWeb/Models/Trip.cs
using FluentValidation;
using System.ComponentModel.DataAnnotations;

namespace Trips.Models
{
    public class Trip
    {
        [Key]
        public int tripId { get; set; }
        public string Destination { get; set; } 
        public string Title { get; set; }
        public string Description { get; set; }

        [Display(Name = "Start Date")]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        public DateTime StartDate { get; set; }

        [Display(Name = "End Date")]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        public DateTime EndDate { get; set; }

        public ICollection<Reservation> Reservation { get; set; }


    }
    


}

TripWeb/Controllers/TripsController.cs
using AutoMapper;
using FluentValidation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using Trips.Data;
using Trips.Models;
using Trips.Repositories.RepositoryTrip;
using Trips.Services.TripService;
using Trips.ViewModel;


namespace Trips.Controllers
{
    public class TripsController : Controller
    {
        private  readonly ITripService _tripService;
        private readonly ITripRepository _tripRepository;
        private readonly IValidator<CreateTripViewModel> _validator;
        private readonly IMapper _mapper;

        public TripsController(ITripService tripService, IValidator<CreateTripViewModel> validator, IMapper mapper)
        {
            _tripService = tripService;
            _validator = validator;
            _mapper = mapper;

        }
        [Authorize (Roles="admin")]
        [HttpGet]
        public ActionResult Create()
        {

            return View();
        }


        [HttpPost]
        public ActionResult Create(CreateTripViewModel tripViewModel)
        {
            var validationResult = _validator.Validate(tripViewModel);

            if (!validationResult.IsValid)
            {
                //Walidacja nie powiodła sie
                foreach (var error in validationResult.Errors)
                {
                    ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                }
                return View(tripViewModel);
            }

            var trip = _mapper.Map<Trip>(tripViewModel);
            //Walidacja powiodla sie, zapisz
            _tripService.CreateTrips(trip);
            return RedirectToAction("Index", "Home");
        }


        [HttpGet]
        public ActionResult Details(int tripId)
        {
            /*var trip = _tripService.GetByIdTrips(tripId);
            if (trip == null){return NotFound();}

            return View("Details", trip);
*/
            var trips = _tripService.GetAllTrips();



            var trip = trips.FirstOrDefault(trip => trip.tripId == tripId);
            if (trip != null)
            {
                var viewModel = new TripDetailsViewModel
                {
                    Id = trip.tripId,
                    Title = trip.Title,
                    StartDate = trip.StartDate,
                    EndDate = trip.EndDate,
                    Price = 999,
                    Destination = trip.Destination,
                    Description = trip.Description
                };


                return View(viewModel);
            }





           return NotFound();

        }

        [HttpGet]
        public ActionResult Update(int tripId)
        {
            var trip = _tripService.GetByIdTrips(tripId);
            if (trip == null){return NotFound();}

            return View("Update", trip);
        }



        [HttpPost]
        public ActionResult UpdateTrip(Trip trip)
        {
            if (ModelState.IsValid)
            {
                _tripService.UpdateTrips(trip);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View("Details", trip); 
            }
        }


        [HttpGet]
        public ActionResult Delete(int tripId)
        {
            Trip trip = _tripService.GetByIdTrips(tripId);
            if (trip == null){return NotFound();}

            _tripService.DeleteTrips(tripId);

            return RedirectToAction("Index", "Home");
        }


        public ActionResult Index()
        {
            var trips = _tripRepository.GetAll();



            List<TripDetailsViewModel> viewModels = trips.Select(t => new TripDetailsViewModel
            {
                Id = t.tripId,
                Title = t.Title,
                StartDate = t.StartDate,
                EndDate = t.EndDate,
                Price = 999,
                Destination = t.Destination,
            }).ToList();




            return View(viewModels);
        }


   



    }
}

TripWeb/Views/Trips/Create.cshtml
@model Trips.ViewModel.CreateTripViewModel
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Trip</h4>
<hr />
<div class="row">

    <form asp-action="Create" method="post" asp-controller="Trips">
        <div asp-validation-summary="ModelOnly" class=""></div>
        <div class="form-group">
            <label asp-for="Title" class="control-label"></label>
            <input asp-for="Title" class="form-control" required />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Description" class="control-label"></label>
            <input asp-for="Description" class="form-control" required />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Destination" class="control-label"></label>
            <input asp-for="Destination" class="form-control" required />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="StartDate" class="control-label"></label>
            <input asp-for="StartDate" class="form-control" type="date" required />
            <span asp-validation-for="StartDate" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="EndDate" class="control-label"></label>
            <input asp-for="EndDate" class="form-control" type="date" required />
            <span asp-validation-for="EndDate" class="text-danger"></span>
        </div>

        <div class="form-group my-4">
            <input type="submit" value="Create" class="btn btn-success" />
        </div>
    </form>

</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

TripWeb/Views/Trips/Details.cshtml
<link rel="stylesheet" href="~/css/details.css" asp-append-version="true" />
@model Trips.ViewModel.TripDetailsViewModel

@{
    ViewData["Title"] = "Details";
}

@* <div>
    <h4 class="title mt-3">Details</h4>
    <hr class="divider" />
    <div class="details-row">
        <div class="details-col-left fw-bold">
            @Html.DisplayNameFor(model => model.Title)
        </div>
        <div class="details-col-right">
            @Html.DisplayFor(model => model.Title)
        </div>

        <div class="details-col-left fw-bold">
            @Html.DisplayNameFor(model => model.Description)
        </div>
        <div class="details-col-right">
            @Html.DisplayFor(model => model.Description)
        </div>


        <div class="details-col-left fw-bold">
            @Html.DisplayNameFor(model => model.Destination)
        </div>
        <div class="details-col-right">
            @Html.DisplayFor(model => model.Destination)
        </div>



        <div class="details-col-left fw-bold">
            @Html.DisplayNameFor(model => model.StartDate)
        </div>
        <div class="details-col-right">
            @Html.DisplayFor(model => model.StartDate)
        </div>

        <div class="details-col-left fw-bold">
            @Html.DisplayNameFor(model => model.EndDate)
        </div>
        <div class="details-col-right">
            @Html.DisplayFor(model => model.EndDate)
        </div>


    </div>
</div>
 *@


 <div>
    <p>Title: @Model.Title</p>
    <p>Price: @Model.Price</p>
    <p>Start Date: @Model.StartDate</p>
    <p>End date: @Model.EndDate</p>
    <p>Location: @Model.Location</p>
    <p>Description: @Model.Description</p>
    <p>Destination: @Model.Destination</p>




 </div>








@* <a class="update-btn btn" asp-action="Update" asp-controller="Trips" asp-route-tripId="@Model.tripId">Update</a> *@
<div class="back-link">
    <a asp-action="Index" asp-controller="Home">Back to List</a>
</div>

TripWeb/Views/Trips/Update.cshtml
@model Trips.Models.Trip
@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>

<h4>Trip</h4>
<hr />
<div class="row">
    <form asp-action="UpdateTrip" method="post" asp-controller="Trips">
        <input type="hidden" asp-for="tripId" />

        <div class="form-group">
            <label asp-for="Title" class="control-label"></label>
            <input asp-for="Title" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Description" class="control-label"></label>
            <input asp-for="Description" class="form-control" />
        </div>

        <div class="form-group">
            <label asp-for="Destination" class="control-label"></label>
            <input asp-for="Destination" class="form-control" required />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="StartDate" class="control-label"></label>
            <input asp-for="StartDate" class="form-control" type="date"/>
        </div>
        <div class="form-group">
            <label asp-for="EndDate" class="control-label"></label>
            <input asp-for="EndDate" class="form-control" type="date" />
        </div>

        <div class="form-group my-4">
            <input type="submit" value="Update" class="btn btn-primary" />
        </div>
    </form>
</div>

<div>
    <a asp-action="Index" asp-controller="Home">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}